/**
 * Brand Icons Build Script
 *
 * This script builds a sanitized library of brand icons from Simple Icons.
 * All SVGs are sanitized using DOMPurify to prevent XSS attacks.
 *
 * Source: https://simpleicons.org
 * License: MIT
 *
 * Usage: npx tsx scripts/build-brand-icons.ts
 */

import simpleIcons from 'simple-icons'
import DOMPurify from 'isomorphic-dompurify'
import fs from 'fs'
import path from 'path'

interface IconMap {
  [key: string]: string
}

// Security: Strict whitelist for SVG elements and attributes
const SVG_PURIFY_CONFIG = {
  USE_PROFILES: { svg: true },
  KEEP_CONTENT: true,
  ALLOWED_TAGS: ['svg', 'path', 'circle', 'rect', 'polygon', 'ellipse', 'line', 'g', 'title'],
  ALLOWED_ATTR: [
    'viewBox',
    'width',
    'height',
    'fill',
    'd',
    'cx',
    'cy',
    'r',
    'x',
    'y',
    'x1',
    'y1',
    'x2',
    'y2',
    'rx',
    'ry',
    'transform',
    'stroke',
    'stroke-width',
    'stroke-linecap',
    'stroke-linejoin',
    'opacity'
  ],
  FORBID_ATTR: ['onload', 'onerror', 'onclick', 'onmouseover', 'xmlns'],
  FORBID_TAGS: ['script', 'embed', 'iframe', 'object', 'link']
}

function validateSVG(svg: string, iconName: string): boolean {
  // Ensure SVG starts with <svg tag
  if (!svg.startsWith('<svg')) {
    console.warn(`[SKIP] ${iconName}: Invalid SVG - doesn't start with <svg`)
    return false
  }

  // Ensure viewBox is present (required for proper scaling)
  if (!svg.includes('viewBox')) {
    console.warn(`[SKIP] ${iconName}: Invalid SVG - missing viewBox`)
    return false
  }

  // Ensure no script tags (double-check after sanitization)
  if (svg.includes('<script') || svg.includes('javascript:')) {
    console.warn(`[SKIP] ${iconName}: Invalid SVG - contains forbidden content`)
    return false
  }

  return true
}

function sanitizeIcon(svg: string, iconName: string): string | null {
  // First, sanitize with DOMPurify using strict config
  const cleanSvg = DOMPurify.sanitize(svg, SVG_PURIFY_CONFIG)

  // Then validate the SVG structure
  if (!validateSVG(cleanSvg, iconName)) {
    return null
  }

  // Remove any existing xmlns attributes (we'll let React handle it)
  return cleanSvg.replace(/\s+xmlns[^=]*="[^"]*"/g, '')
}

function buildIconLibrary(): IconMap {
  const iconMap: IconMap = {}
  let skipped = 0

  console.log('🔨 Building brand icon library from Simple Icons...')
  console.log(`📦 Processing ${Object.keys(simpleIcons).length} icons...`)

  for (const [key, icon] of Object.entries(simpleIcons)) {
    if (typeof icon.svg === 'string') {
      const sanitizedSvg = sanitizeIcon(icon.svg, key)

      if (sanitizedSvg) {
        // Use the slug (lowercase, no spaces) as the key
        iconMap[key] = sanitizedSvg
      } else {
        skipped++
      }
    }
  }

  console.log(`✅ Built ${Object.keys(iconMap).length} icons`)
  if (skipped > 0) {
    console.log(`⚠️  Skipped ${skipped} invalid icons`)
  }

  return iconMap
}

function generateTypeDefinitions(iconMap: IconMap): string {
  const iconKeys = Object.keys(iconMap).sort()
  return `
// Auto-generated type definitions for brand icons
// Generated from Simple Icons library

export type BrandSlug =
  ${iconKeys.map(k => `  | '${k}'`).join('\n')}

export type BrandSlugWithOptional = BrandSlug | 'installora' | 'default'
`
}

function main() {
  // Build the icon library
  const iconMap = buildIconLibrary()

  // Generate TypeScript output
  const output = `// Auto-generated from Simple Icons with DOMPurify sanitization
// Source: https://simpleicons.org
// License: MIT
// Generated: ${new Date().toISOString()}
//
// SECURITY: All SVGs have been sanitized using DOMPurify with strict whitelist.
// Only safe SVG elements and attributes are allowed.
//
// DO NOT EDIT THIS FILE MANUALLY - it will be overwritten

export const icons = ${JSON.stringify(iconMap, null, 2)} as const

${generateTypeDefinitions(iconMap)}

/**
 * Get a brand icon by slug
 * @param slug - The brand slug (e.g., 'github', 'visualstudiocode')
 * @returns The sanitized SVG string or undefined if not found
 */
export function getIcon(slug: string): string | undefined {
  return icons[slug as keyof typeof icons]
}

/**
 * Check if a brand icon exists
 * @param slug - The brand slug to check
 * @returns true if the icon exists in the library
 */
export function hasIcon(slug: string): boolean {
  return slug in icons
}

/**
 * Get all available brand slugs
 * @returns Array of all brand icon slugs
 */
export function getAllBrandSlugs(): BrandSlug[] {
  return Object.keys(icons) as BrandSlug[]
}
`

  // Ensure lib directory exists
  const libDir = path.join(process.cwd(), 'lib')
  if (!fs.existsSync(libDir)) {
    fs.mkdirSync(libDir, { recursive: true })
  }

  // Write the brand icons library
  const outputPath = path.join(libDir, 'brand-icons.ts')
  fs.writeFileSync(outputPath, output, 'utf-8')

  console.log(`\n✨ Brand icons library written to: ${outputPath}`)
  console.log(`📊 Total size: ${(output.length / 1024).toFixed(2)} KB`)

  // Write a mapping file for common package IDs to brand slugs
  const commonMappings: Record<string, string> = {
    'Git.Git': 'git',
    'Microsoft.VisualStudioCode': 'visualstudiocode',
    'OpenJS.NodeJS.LTS': 'nodejs',
    'Python.Python.3.13': 'python',
    'Docker.DockerDesktop': 'docker',
    'Google.Chrome': 'googlechrome',
    'Mozilla.Firefox': 'firefox',
    'Microsoft.Edge': 'microsoftedge',
    'Microsoft.VisualStudio.2022.BuildTools': 'visualstudio',
    'Microsoft.WindowsTerminal': 'windows',
    'OpenJS.NodeJS': 'nodejs',
    'Python.Python': 'python',
    'Golang.Go': 'go',
    'Rustlang.Rust.MSVC': 'rust',
    'Java.OpenJDK': 'openjdk',
    'Adobe.Acrobat.Reader.64-bit': 'adobe',
    'Microsoft.OneDrive': 'microsoftonedrive',
    'Spotify.Spotify': 'spotify',
    'Valve.Steam': 'steam',
    'Discord.Discord': 'discord',
    'Slack.Slack': 'slack',
    'Notion.Notion': 'notion',
    'Tencent.WeChat': 'wechat',
    'Microsoft.Teams': 'microsoftteams',
    'Zoom.Zoom': 'zoom',
    'VideoLAN.VLC': 'vlcmediaplayer',
    'Bitwarden.Bitwarden': 'bitwarden',
    '1Password.1Password': '1password',
    'Microsoft.PowerToys': 'microsoft',
    'Microsoft.WindowsSDK': 'windows',
    'GitHub.cli': 'github',
    'GitExtensionsTeam.GitExtensions': 'git',
    'TortoiseGit.TortoiseGit': 'git',
  }

  const mappingPath = path.join(libDir, 'brand-icon-mappings.ts')
  const mappingOutput = `// Auto-generated mappings from winget package IDs to Simple Icons brand slugs
// This helps map package IDs to their brand icons

export const packageIdToBrandSlug: Record<string, string> = ${JSON.stringify(commonMappings, null, 2)}

/**
 * Get the brand slug for a winget package ID
 * @param packageId - The winget package ID (e.g., 'Microsoft.VisualStudioCode')
 * @returns The brand slug or undefined if no mapping exists
 */
export function getBrandSlugForPackage(packageId: string): string | undefined {
  return packageIdToBrandSlug[packageId]
}

/**
 * Extract a potential brand slug from a package ID
 * This tries to guess the brand from the publisher name
 * @param packageId - The winget package ID
 * @returns A guessed brand slug or undefined
 */
export function guessBrandSlug(packageId: string): string | undefined {
  // Extract publisher name (part before the dot)
  const match = packageId.match(/^([^.]+)\./)
  if (!match) return undefined

  const publisher = match[1].toLowerCase()
  const appName = packageId.substring(packageId.indexOf('.') + 1).toLowerCase()

  // Try some common transformations
  const candidates = [
    publisher,              // 'microsoft' from Microsoft.VisualStudioCode
    appName,                // 'visualstudiocode' from Microsoft.VisualStudioCode
    publisher + appName,    // 'microsoftvisualstudiocode'
    appName.replace(/\./g, ''), // 'visualstudiocode' from Visual.Studio.Code
    publisher.replace(/\./g, '') + appName,
  ]

  return candidates
}
`
  fs.writeFileSync(mappingPath, mappingOutput, 'utf-8')
  console.log(`📝 Mappings written to: ${mappingPath}`)

  console.log('\n✅ Build complete!')
}

main()
